/*******************************************************************************************************************************
This file is a part of the EvoDesign physical Energy Function (EvoEF)

Copyright (c) 2019 Xiaoqiang Huang (tommyhuangthu@foxmail.com, xiaoqiah@umich.edu)

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation 
files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, 
modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the 
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES 
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE 
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR 
IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
********************************************************************************************************************************/

#ifndef FOLDEF_H
#define FOLDEF_H

#include "Residue.h"

#define FOLDEF_GEN_volume_H     0.0
#define FOLDEF_GEN_radius_H     0.0
#define FOLDEF_GEN_Occmin_H     0.0
#define FOLDEF_GEN_Occmax_H     100.0
#define FOLDEF_GEN_VDWene_H     0.0
#define FOLDEF_GEN_SolEne_H     0.0

#define FOLDEF_BKB_volume_N     13.30
#define FOLDEF_BKB_volume_CA    9.400
#define FOLDEF_BKB_volume_C     9.820
#define FOLDEF_BKB_volume_O     8.200
#define FOLDEF_ALA_volume_CB    16.15
#define FOLDEF_ARG_volume_CB    12.77
#define FOLDEF_ARG_volume_CG    12.77
#define FOLDEF_ARG_volume_CD    12.77
#define FOLDEF_ARG_volume_NE    9.000
#define FOLDEF_ARG_volume_CZ    6.950
#define FOLDEF_ARG_volume_NH1   9.000
#define FOLDEF_ARG_volume_NH2   9.000
#define FOLDEF_ASN_volume_CB    12.77
#define FOLDEF_ASN_volume_CG    9.820
#define FOLDEF_ASN_volume_OD1   8.170
#define FOLDEF_ASN_volume_ND2   13.25
#define FOLDEF_ASP_volume_CB    12.77
#define FOLDEF_ASP_volume_CG    9.820
#define FOLDEF_ASP_volume_OD1   8.170
#define FOLDEF_ASP_volume_OD2   8.170
#define FOLDEF_CYS_volume_CB    12.77
#define FOLDEF_CYS_volume_SG    19.93
#define FOLDEF_GLU_volume_CB    12.77
#define FOLDEF_GLU_volume_CG    12.77
#define FOLDEF_GLU_volume_CD    9.820
#define FOLDEF_GLU_volume_OE1   8.170
#define FOLDEF_GLU_volume_OE2   8.170
#define FOLDEF_GLY_volume_CA    12.80
#define FOLDEF_PHE_volume_CB    12.77
#define FOLDEF_PHE_volume_CG    7.260
#define FOLDEF_PHE_volume_CD1   10.80
#define FOLDEF_PHE_volume_CD2   10.80
#define FOLDEF_PHE_volume_CE1   10.80
#define FOLDEF_PHE_volume_CE2   10.80
#define FOLDEF_PHE_volume_CZ    10.80
#define FOLDEF_PRO_volume_CB    12.77
#define FOLDEF_PRO_volume_CG    12.77
#define FOLDEF_PRO_volume_CD    12.77
#define FOLDEF_GLN_volume_CB    12.77
#define FOLDEF_GLN_volume_CG    12.77
#define FOLDEF_GLN_volume_CD    9.820
#define FOLDEF_GLN_volume_OE1   8.170
#define FOLDEF_GLN_volume_NE2   13.25
#define FOLDEF_HIS_volume_CB    12.77
#define FOLDEF_HIS_volume_CG    7.260
#define FOLDEF_HIS_volume_ND1   9.250
#define FOLDEF_HIS_volume_CD2   10.80
#define FOLDEF_HIS_volume_CE1   10.80
#define FOLDEF_HIS_volume_NE2   9.250
#define FOLDEF_ILE_volume_CB    9.400
#define FOLDEF_ILE_volume_CG1   12.77
#define FOLDEF_ILE_volume_CG2   16.15
#define FOLDEF_ILE_volume_CD    16.15
#define FOLDEF_LEU_volume_CB    12.77
#define FOLDEF_LEU_volume_CG    9.400
#define FOLDEF_LEU_volume_CD1   16.15
#define FOLDEF_LEU_volume_CD2   16.15
#define FOLDEF_LYS_volume_CB    12.77
#define FOLDEF_LYS_volume_CG    12.77
#define FOLDEF_LYS_volume_CD    12.77
#define FOLDEF_LYS_volume_CE    12.77
#define FOLDEF_LYS_volume_NZ    13.25
#define FOLDEF_MET_volume_CB    12.77
#define FOLDEF_MET_volume_CG    12.77
#define FOLDEF_MET_volume_SD    16.39
#define FOLDEF_MET_volume_CE    12.77
#define FOLDEF_TRP_volume_CB    12.77
#define FOLDEF_TRP_volume_CG    7.260
#define FOLDEF_TRP_volume_CD1   10.80
#define FOLDEF_TRP_volume_CD2   6.800
#define FOLDEF_TRP_volume_NE1   9.000
#define FOLDEF_TRP_volume_CE2   6.800
#define FOLDEF_TRP_volume_CE3   10.80
#define FOLDEF_TRP_volume_CZ2   10.80
#define FOLDEF_TRP_volume_CZ3   10.80
#define FOLDEF_TRP_volume_CH2   10.80
#define FOLDEF_SER_volume_CB    12.77
#define FOLDEF_SER_volume_OG    11.04
#define FOLDEF_THR_volume_CB    9.400
#define FOLDEF_THR_volume_OG1   11.04
#define FOLDEF_THR_volume_CG2   16.15
#define FOLDEF_TYR_volume_CB    12.77
#define FOLDEF_TYR_volume_CG    7.260
#define FOLDEF_TYR_volume_CD1   10.80
#define FOLDEF_TYR_volume_CD2   10.80
#define FOLDEF_TYR_volume_CE1   10.80
#define FOLDEF_TYR_volume_CE2   10.80
#define FOLDEF_TYR_volume_CZ    10.80
#define FOLDEF_TYR_volume_OH    10.80
#define FOLDEF_VAL_volume_CB    9.400
#define FOLDEF_VAL_volume_CG1   16.15
#define FOLDEF_VAL_volume_CG2   16.15
#define FOLDEF_HOH_volume_HOH   0.000

#define FOLDEF_BKB_radius_N     1.650
#define FOLDEF_BKB_radius_CA    1.800
#define FOLDEF_BKB_radius_C     1.400
#define FOLDEF_BKB_radius_O     1.400
#define FOLDEF_ALA_radius_CB    1.900
#define FOLDEF_ARG_radius_CB    1.900
#define FOLDEF_ARG_radius_CG    1.900
#define FOLDEF_ARG_radius_CD    1.900
#define FOLDEF_ARG_radius_NE    1.650
#define FOLDEF_ARG_radius_CZ    1.400
#define FOLDEF_ARG_radius_NH1   1.650
#define FOLDEF_ARG_radius_NH2   1.650
#define FOLDEF_ASN_radius_CB    1.900
#define FOLDEF_ASN_radius_CG    1.900
#define FOLDEF_ASN_radius_OD1   1.400
#define FOLDEF_ASN_radius_ND2   1.650
#define FOLDEF_ASP_radius_CB    1.900
#define FOLDEF_ASP_radius_CG    1.900
#define FOLDEF_ASP_radius_OD1   1.400
#define FOLDEF_ASP_radius_OD2   1.400
#define FOLDEF_CYS_radius_CB    1.900
#define FOLDEF_CYS_radius_SG    1.850
#define FOLDEF_GLU_radius_CB    1.900
#define FOLDEF_GLU_radius_CG    1.900
#define FOLDEF_GLU_radius_CD    1.900
#define FOLDEF_GLU_radius_OE1   1.400
#define FOLDEF_GLU_radius_OE2   1.400
#define FOLDEF_GLY_radius_CA    1.900
#define FOLDEF_PHE_radius_CB    1.900
#define FOLDEF_PHE_radius_CG    1.800
#define FOLDEF_PHE_radius_CD1   1.800
#define FOLDEF_PHE_radius_CD2   1.800
#define FOLDEF_PHE_radius_CE1   1.800
#define FOLDEF_PHE_radius_CE2   1.800
#define FOLDEF_PHE_radius_CZ    1.800
#define FOLDEF_PRO_radius_CB    1.900
#define FOLDEF_PRO_radius_CG    1.900
#define FOLDEF_PRO_radius_CD    1.900
#define FOLDEF_GLN_radius_CB    1.900
#define FOLDEF_GLN_radius_CG    1.900
#define FOLDEF_GLN_radius_CD    1.900
#define FOLDEF_GLN_radius_OE1   1.400
#define FOLDEF_GLN_radius_NE2   1.650
#define FOLDEF_HIS_radius_CB    1.900
#define FOLDEF_HIS_radius_CG    1.900
#define FOLDEF_HIS_radius_ND1   1.650
#define FOLDEF_HIS_radius_CD2   1.900
#define FOLDEF_HIS_radius_CE1   1.900
#define FOLDEF_HIS_radius_NE2   1.650
#define FOLDEF_ILE_radius_CB    1.800
#define FOLDEF_ILE_radius_CG1   1.900
#define FOLDEF_ILE_radius_CG2   1.900
#define FOLDEF_ILE_radius_CD    1.900
#define FOLDEF_LEU_radius_CB    1.900
#define FOLDEF_LEU_radius_CG    1.900
#define FOLDEF_LEU_radius_CD1   1.900
#define FOLDEF_LEU_radius_CD2   1.900
#define FOLDEF_LYS_radius_CB    1.900
#define FOLDEF_LYS_radius_CG    1.900
#define FOLDEF_LYS_radius_CD    1.900
#define FOLDEF_LYS_radius_CE    1.900
#define FOLDEF_LYS_radius_NZ    1.650
#define FOLDEF_MET_radius_CB    1.900
#define FOLDEF_MET_radius_CG    1.900
#define FOLDEF_MET_radius_SD    1.850
#define FOLDEF_MET_radius_CE    1.900
#define FOLDEF_TRP_radius_CB    1.900
#define FOLDEF_TRP_radius_CG    1.900
#define FOLDEF_TRP_radius_CD1   1.900
#define FOLDEF_TRP_radius_CD2   1.900
#define FOLDEF_TRP_radius_NE1   1.650
#define FOLDEF_TRP_radius_CE2   1.900
#define FOLDEF_TRP_radius_CE3   1.900
#define FOLDEF_TRP_radius_CZ2   1.900
#define FOLDEF_TRP_radius_CZ3   1.900
#define FOLDEF_TRP_radius_CH2   1.900
#define FOLDEF_SER_radius_CB    1.900
#define FOLDEF_SER_radius_OG    1.400
#define FOLDEF_THR_radius_CB    1.800
#define FOLDEF_THR_radius_OG1   1.400
#define FOLDEF_THR_radius_CG2   1.900
#define FOLDEF_TYR_radius_CB    1.900
#define FOLDEF_TYR_radius_CG    1.800
#define FOLDEF_TYR_radius_CD1   1.800
#define FOLDEF_TYR_radius_CD2   1.800
#define FOLDEF_TYR_radius_CE1   1.800
#define FOLDEF_TYR_radius_CE2   1.800
#define FOLDEF_TYR_radius_CZ    1.800
#define FOLDEF_TYR_radius_OH    1.400
#define FOLDEF_VAL_radius_CB    1.800
#define FOLDEF_VAL_radius_CG1   1.900
#define FOLDEF_VAL_radius_CG2   1.900
#define FOLDEF_HOH_radius_HOH   1.400

#define FOLDEF_BKB_Occmin_N     112
#define FOLDEF_BKB_Occmin_CA    120
#define FOLDEF_BKB_Occmin_C     120
#define FOLDEF_BKB_Occmin_O     109
#define FOLDEF_ALA_Occmin_CB    82 
#define FOLDEF_ARG_Occmin_CB    133
#define FOLDEF_ARG_Occmin_CG    131
#define FOLDEF_ARG_Occmin_CD    98 
#define FOLDEF_ARG_Occmin_NE    75 
#define FOLDEF_ARG_Occmin_CZ    62 
#define FOLDEF_ARG_Occmin_NH1   57 
#define FOLDEF_ARG_Occmin_NH2   50 
#define FOLDEF_ASN_Occmin_CB    127
#define FOLDEF_ASN_Occmin_CG    113
#define FOLDEF_ASN_Occmin_OD1   79 
#define FOLDEF_ASN_Occmin_ND2   128
#define FOLDEF_ASP_Occmin_CB    122
#define FOLDEF_ASP_Occmin_CG    105
#define FOLDEF_ASP_Occmin_OD1   94 
#define FOLDEF_ASP_Occmin_OD2   94 
#define FOLDEF_CYS_Occmin_CB    115
#define FOLDEF_CYS_Occmin_SG    99 
#define FOLDEF_GLU_Occmin_CB    134
#define FOLDEF_GLU_Occmin_CG    121
#define FOLDEF_GLU_Occmin_CD    79 
#define FOLDEF_GLU_Occmin_OE1   65 
#define FOLDEF_GLU_Occmin_OE2   65 
#define FOLDEF_GLY_Occmin_CA    102
#define FOLDEF_PHE_Occmin_CB    148
#define FOLDEF_PHE_Occmin_CG    142
#define FOLDEF_PHE_Occmin_CD1   131
#define FOLDEF_PHE_Occmin_CD2   131
#define FOLDEF_PHE_Occmin_CE1   103
#define FOLDEF_PHE_Occmin_CE2   103
#define FOLDEF_PHE_Occmin_CZ    92 
#define FOLDEF_PRO_Occmin_CB    115
#define FOLDEF_PRO_Occmin_CG    107
#define FOLDEF_PRO_Occmin_CD    132
#define FOLDEF_GLN_Occmin_CB    134
#define FOLDEF_GLN_Occmin_CG    126
#define FOLDEF_GLN_Occmin_CD    84 
#define FOLDEF_GLN_Occmin_OE1   65 
#define FOLDEF_GLN_Occmin_NE2   76 
#define FOLDEF_HIS_Occmin_CB    140
#define FOLDEF_HIS_Occmin_CG    128
#define FOLDEF_HIS_Occmin_ND1   116
#define FOLDEF_HIS_Occmin_CD2   114
#define FOLDEF_HIS_Occmin_CE1   91 
#define FOLDEF_HIS_Occmin_NE2   90 
#define FOLDEF_ILE_Occmin_CB    137
#define FOLDEF_ILE_Occmin_CG1   123
#define FOLDEF_ILE_Occmin_CG2   123
#define FOLDEF_ILE_Occmin_CD    81 
#define FOLDEF_LEU_Occmin_CB    138
#define FOLDEF_LEU_Occmin_CG    121
#define FOLDEF_LEU_Occmin_CD1   103
#define FOLDEF_LEU_Occmin_CD2   103
#define FOLDEF_LYS_Occmin_CB    136
#define FOLDEF_LYS_Occmin_CG    130
#define FOLDEF_LYS_Occmin_CD    91 
#define FOLDEF_LYS_Occmin_CE    71 
#define FOLDEF_LYS_Occmin_NZ    53 
#define FOLDEF_MET_Occmin_CB    136
#define FOLDEF_MET_Occmin_CG    127
#define FOLDEF_MET_Occmin_SD    80 
#define FOLDEF_MET_Occmin_CE    62 
#define FOLDEF_TRP_Occmin_CB    158
#define FOLDEF_TRP_Occmin_CG    158
#define FOLDEF_TRP_Occmin_CD1   138
#define FOLDEF_TRP_Occmin_CD2   153
#define FOLDEF_TRP_Occmin_NE1   120
#define FOLDEF_TRP_Occmin_CE2   127
#define FOLDEF_TRP_Occmin_CE3   151
#define FOLDEF_TRP_Occmin_CZ2   103
#define FOLDEF_TRP_Occmin_CZ3   119
#define FOLDEF_TRP_Occmin_CH2   98 
#define FOLDEF_SER_Occmin_CB    107
#define FOLDEF_SER_Occmin_OG    93 
#define FOLDEF_THR_Occmin_CB    120
#define FOLDEF_THR_Occmin_OG1   111
#define FOLDEF_THR_Occmin_CG2   107
#define FOLDEF_TYR_Occmin_CB    147
#define FOLDEF_TYR_Occmin_CG    146
#define FOLDEF_TYR_Occmin_CD1   136
#define FOLDEF_TYR_Occmin_CD2   137
#define FOLDEF_TYR_Occmin_CE1   110
#define FOLDEF_TYR_Occmin_CE2   110
#define FOLDEF_TYR_Occmin_CZ    99 
#define FOLDEF_TYR_Occmin_OH    70 
#define FOLDEF_VAL_Occmin_CB    125
#define FOLDEF_VAL_Occmin_CG1   111
#define FOLDEF_VAL_Occmin_CG2   111
#define FOLDEF_HOH_Occmin_HOH   30 

#define FOLDEF_BKB_Occmax_N     250
#define FOLDEF_BKB_Occmax_CA    250
#define FOLDEF_BKB_Occmax_C     250
#define FOLDEF_BKB_Occmax_O     250
#define FOLDEF_ALA_Occmax_CB    250
#define FOLDEF_ARG_Occmax_CB    254
#define FOLDEF_ARG_Occmax_CG    241
#define FOLDEF_ARG_Occmax_CD    231
#define FOLDEF_ARG_Occmax_NE    224
#define FOLDEF_ARG_Occmax_CZ    225
#define FOLDEF_ARG_Occmax_NH1   239
#define FOLDEF_ARG_Occmax_NH2   226
#define FOLDEF_ASN_Occmax_CB    252
#define FOLDEF_ASN_Occmax_CG    254
#define FOLDEF_ASN_Occmax_OD1   266
#define FOLDEF_ASN_Occmax_ND2   257
#define FOLDEF_ASP_Occmax_CB    250
#define FOLDEF_ASP_Occmax_CG    244
#define FOLDEF_ASP_Occmax_OD1   244
#define FOLDEF_ASP_Occmax_OD2   250
#define FOLDEF_CYS_Occmax_CB    261
#define FOLDEF_CYS_Occmax_SG    260
#define FOLDEF_GLU_Occmax_CB    247
#define FOLDEF_GLU_Occmax_CG    238
#define FOLDEF_GLU_Occmax_CD    230
#define FOLDEF_GLU_Occmax_OE1   228
#define FOLDEF_GLU_Occmax_OE2   234
#define FOLDEF_GLY_Occmax_CA    250
#define FOLDEF_PHE_Occmax_CB    252
#define FOLDEF_PHE_Occmax_CG    247
#define FOLDEF_PHE_Occmax_CD1   230
#define FOLDEF_PHE_Occmax_CD2   230
#define FOLDEF_PHE_Occmax_CE1   223
#define FOLDEF_PHE_Occmax_CE2   223
#define FOLDEF_PHE_Occmax_CZ    217
#define FOLDEF_PRO_Occmax_CB    238
#define FOLDEF_PRO_Occmax_CG    238
#define FOLDEF_PRO_Occmax_CD    244
#define FOLDEF_GLN_Occmax_CB    247
#define FOLDEF_GLN_Occmax_CG    235
#define FOLDEF_GLN_Occmax_CD    234
#define FOLDEF_GLN_Occmax_OE1   235
#define FOLDEF_GLN_Occmax_NE2   244
#define FOLDEF_HIS_Occmax_CB    248
#define FOLDEF_HIS_Occmax_CG    239
#define FOLDEF_HIS_Occmax_ND1   237
#define FOLDEF_HIS_Occmax_CD2   246
#define FOLDEF_HIS_Occmax_CE1   230
#define FOLDEF_HIS_Occmax_NE2   233
#define FOLDEF_ILE_Occmax_CB    228
#define FOLDEF_ILE_Occmax_CG1   226
#define FOLDEF_ILE_Occmax_CG2   234
#define FOLDEF_ILE_Occmax_CD    224
#define FOLDEF_LEU_Occmax_CB    234
#define FOLDEF_LEU_Occmax_CG    215
#define FOLDEF_LEU_Occmax_CD1   224
#define FOLDEF_LEU_Occmax_CD2   224
#define FOLDEF_LYS_Occmax_CB    245
#define FOLDEF_LYS_Occmax_CG    223
#define FOLDEF_LYS_Occmax_CD    209
#define FOLDEF_LYS_Occmax_CE    195
#define FOLDEF_LYS_Occmax_NZ    192
#define FOLDEF_MET_Occmax_CB    246
#define FOLDEF_MET_Occmax_CG    235
#define FOLDEF_MET_Occmax_SD    223
#define FOLDEF_MET_Occmax_CE    227
#define FOLDEF_TRP_Occmax_CB    257
#define FOLDEF_TRP_Occmax_CG    248
#define FOLDEF_TRP_Occmax_CD1   255
#define FOLDEF_TRP_Occmax_CD2   231
#define FOLDEF_TRP_Occmax_NE1   246
#define FOLDEF_TRP_Occmax_CE2   226
#define FOLDEF_TRP_Occmax_CE3   243
#define FOLDEF_TRP_Occmax_CZ2   226
#define FOLDEF_TRP_Occmax_CZ3   235
#define FOLDEF_TRP_Occmax_CH2   227
#define FOLDEF_SER_Occmax_CB    256
#define FOLDEF_SER_Occmax_OG    260
#define FOLDEF_THR_Occmax_CB    243
#define FOLDEF_THR_Occmax_OG1   254
#define FOLDEF_THR_Occmax_CG2   243
#define FOLDEF_TYR_Occmax_CB    258
#define FOLDEF_TYR_Occmax_CG    239
#define FOLDEF_TYR_Occmax_CD1   242
#define FOLDEF_TYR_Occmax_CD2   242
#define FOLDEF_TYR_Occmax_CE1   234
#define FOLDEF_TYR_Occmax_CE2   234
#define FOLDEF_TYR_Occmax_CZ    229
#define FOLDEF_TYR_Occmax_OH    234
#define FOLDEF_VAL_Occmax_CB    232
#define FOLDEF_VAL_Occmax_CG1   224
#define FOLDEF_VAL_Occmax_CG2   224
#define FOLDEF_HOH_Occmax_HOH   250

#define FOLDEF_BKB_VDWene_N     -1.0906
#define FOLDEF_BKB_VDWene_CA    -0.7708
#define FOLDEF_BKB_VDWene_C     -0.8052
#define FOLDEF_BKB_VDWene_O     -0.6724
#define FOLDEF_ALA_VDWene_CB    -1.3243
#define FOLDEF_ARG_VDWene_CB    -1.0471
#define FOLDEF_ARG_VDWene_CG    -1.0471
#define FOLDEF_ARG_VDWene_CD    -1.0471
#define FOLDEF_ARG_VDWene_NE    -0.7380
#define FOLDEF_ARG_VDWene_CZ    -0.5699
#define FOLDEF_ARG_VDWene_NH1   -0.7380
#define FOLDEF_ARG_VDWene_NH2   -0.7380
#define FOLDEF_ASN_VDWene_CB    -1.0471
#define FOLDEF_ASN_VDWene_CG    -0.8052
#define FOLDEF_ASN_VDWene_OD1   -0.6699
#define FOLDEF_ASN_VDWene_ND2   -1.0865
#define FOLDEF_ASP_VDWene_CB    -1.0471
#define FOLDEF_ASP_VDWene_CG    -0.8052
#define FOLDEF_ASP_VDWene_OD1   -0.6699
#define FOLDEF_ASP_VDWene_OD2   -0.6699
#define FOLDEF_CYS_VDWene_CB    -1.0471
#define FOLDEF_CYS_VDWene_SG    -1.6343
#define FOLDEF_GLU_VDWene_CB    -1.0471
#define FOLDEF_GLU_VDWene_CG    -1.0471
#define FOLDEF_GLU_VDWene_CD    -0.8052
#define FOLDEF_GLU_VDWene_OE1   -0.6699
#define FOLDEF_GLU_VDWene_OE2   -0.6699
#define FOLDEF_GLY_VDWene_CA    -1.0496
#define FOLDEF_PHE_VDWene_CB    -1.0471
#define FOLDEF_PHE_VDWene_CG    -0.5953
#define FOLDEF_PHE_VDWene_CD1   -0.8856
#define FOLDEF_PHE_VDWene_CD2   -0.8856
#define FOLDEF_PHE_VDWene_CE1   -0.8856
#define FOLDEF_PHE_VDWene_CE2   -0.8856
#define FOLDEF_PHE_VDWene_CZ    -0.8856
#define FOLDEF_PRO_VDWene_CB    -1.0471
#define FOLDEF_PRO_VDWene_CG    -1.0471
#define FOLDEF_PRO_VDWene_CD    -1.0471
#define FOLDEF_GLN_VDWene_CB    -1.0471
#define FOLDEF_GLN_VDWene_CG    -1.0471
#define FOLDEF_GLN_VDWene_CD    -0.8052
#define FOLDEF_GLN_VDWene_OE1   -0.6699
#define FOLDEF_GLN_VDWene_NE2   -1.0865
#define FOLDEF_HIS_VDWene_CB    -1.0471
#define FOLDEF_HIS_VDWene_CG    -0.5953
#define FOLDEF_HIS_VDWene_ND1   -0.7585
#define FOLDEF_HIS_VDWene_CD2   -0.8856
#define FOLDEF_HIS_VDWene_CE1   -0.8856
#define FOLDEF_HIS_VDWene_NE2   -0.7585
#define FOLDEF_ILE_VDWene_CB    -0.7708
#define FOLDEF_ILE_VDWene_CG1   -1.0471
#define FOLDEF_ILE_VDWene_CG2   -1.3243
#define FOLDEF_ILE_VDWene_CD    -1.3243
#define FOLDEF_LEU_VDWene_CB    -1.0471
#define FOLDEF_LEU_VDWene_CG    -0.7708
#define FOLDEF_LEU_VDWene_CD1   -1.3243
#define FOLDEF_LEU_VDWene_CD2   -1.3243
#define FOLDEF_LYS_VDWene_CB    -1.0471
#define FOLDEF_LYS_VDWene_CG    -1.0471
#define FOLDEF_LYS_VDWene_CD    -1.0471
#define FOLDEF_LYS_VDWene_CE    -1.0471
#define FOLDEF_LYS_VDWene_NZ    -1.0865
#define FOLDEF_MET_VDWene_CB    -1.0471
#define FOLDEF_MET_VDWene_CG    -1.0471
#define FOLDEF_MET_VDWene_SD    -1.3440
#define FOLDEF_MET_VDWene_CE    -1.0471
#define FOLDEF_TRP_VDWene_CB    -1.0471
#define FOLDEF_TRP_VDWene_CG    -0.5953
#define FOLDEF_TRP_VDWene_CD1   -0.8856
#define FOLDEF_TRP_VDWene_CD2   -0.5576
#define FOLDEF_TRP_VDWene_NE1   -0.7380
#define FOLDEF_TRP_VDWene_CE2   -0.5576
#define FOLDEF_TRP_VDWene_CE3   -0.8856
#define FOLDEF_TRP_VDWene_CZ2   -0.8856
#define FOLDEF_TRP_VDWene_CZ3   -0.8856
#define FOLDEF_TRP_VDWene_CH2   -0.8856
#define FOLDEF_SER_VDWene_CB    -1.0471
#define FOLDEF_SER_VDWene_OG    -0.9052
#define FOLDEF_THR_VDWene_CB    -0.7708
#define FOLDEF_THR_VDWene_OG1   -0.9052
#define FOLDEF_THR_VDWene_CG2   -1.3243
#define FOLDEF_TYR_VDWene_CB    -1.0471
#define FOLDEF_TYR_VDWene_CG    -0.5953
#define FOLDEF_TYR_VDWene_CD1   -0.8856
#define FOLDEF_TYR_VDWene_CD2   -0.8856
#define FOLDEF_TYR_VDWene_CE1   -0.8856
#define FOLDEF_TYR_VDWene_CE2   -0.8856
#define FOLDEF_TYR_VDWene_CZ    -0.8856
#define FOLDEF_TYR_VDWene_OH    -0.8856
#define FOLDEF_VAL_VDWene_CB    -0.7708
#define FOLDEF_VAL_VDWene_CG1   -1.3243
#define FOLDEF_VAL_VDWene_CG2   -1.3243
#define FOLDEF_HOH_VDWene_HOH   0.00000

#define FOLDEF_BKB_SolEne_N     0.8000
#define FOLDEF_BKB_SolEne_CA    -0.295
#define FOLDEF_BKB_SolEne_C     -0.308
#define FOLDEF_BKB_SolEne_O     0.8000
#define FOLDEF_ALA_SolEne_CB    -0.507
#define FOLDEF_ARG_SolEne_CB    -0.401
#define FOLDEF_ARG_SolEne_CG    -0.401
#define FOLDEF_ARG_SolEne_CD    -0.401
#define FOLDEF_ARG_SolEne_NE    1.0000
#define FOLDEF_ARG_SolEne_CZ    0.0000
#define FOLDEF_ARG_SolEne_NH1   1.3000
#define FOLDEF_ARG_SolEne_NH2   1.3000
#define FOLDEF_ASN_SolEne_CB    -0.401
#define FOLDEF_ASN_SolEne_CG    -0.308
#define FOLDEF_ASN_SolEne_OD1   0.8000
#define FOLDEF_ASN_SolEne_ND2   0.8000
#define FOLDEF_ASP_SolEne_CB    -0.401
#define FOLDEF_ASP_SolEne_CG    -0.308
#define FOLDEF_ASP_SolEne_OD1   1.4400
#define FOLDEF_ASP_SolEne_OD2   1.4400
#define FOLDEF_CYS_SolEne_CB    -0.401
#define FOLDEF_CYS_SolEne_SG    -0.300
#define FOLDEF_GLU_SolEne_CB    -0.401
#define FOLDEF_GLU_SolEne_CG    -0.401
#define FOLDEF_GLU_SolEne_CD    -0.308
#define FOLDEF_GLU_SolEne_OE1   1.4400
#define FOLDEF_GLU_SolEne_OE2   1.4400
#define FOLDEF_GLY_SolEne_CA    -0.402
#define FOLDEF_PHE_SolEne_CB    -0.401
#define FOLDEF_PHE_SolEne_CG    -0.228
#define FOLDEF_PHE_SolEne_CD1   -0.339
#define FOLDEF_PHE_SolEne_CD2   -0.339
#define FOLDEF_PHE_SolEne_CE1   -0.339
#define FOLDEF_PHE_SolEne_CE2   -0.339
#define FOLDEF_PHE_SolEne_CZ    -0.339
#define FOLDEF_PRO_SolEne_CB    -0.401
#define FOLDEF_PRO_SolEne_CG    -0.401
#define FOLDEF_PRO_SolEne_CD    -0.401
#define FOLDEF_GLN_SolEne_CB    -0.401
#define FOLDEF_GLN_SolEne_CG    -0.401
#define FOLDEF_GLN_SolEne_CD    -0.308
#define FOLDEF_GLN_SolEne_OE1   0.8000
#define FOLDEF_GLN_SolEne_NE2   0.8000
#define FOLDEF_HIS_SolEne_CB    -0.401
#define FOLDEF_HIS_SolEne_CG    -0.228
#define FOLDEF_HIS_SolEne_ND1   0.6400
#define FOLDEF_HIS_SolEne_CD2   -0.339
#define FOLDEF_HIS_SolEne_CE1   -0.339
#define FOLDEF_HIS_SolEne_NE2   0.6400
#define FOLDEF_ILE_SolEne_CB    -0.295
#define FOLDEF_ILE_SolEne_CG1   -0.401
#define FOLDEF_ILE_SolEne_CG2   -0.507
#define FOLDEF_ILE_SolEne_CD    -0.507
#define FOLDEF_LEU_SolEne_CB    -0.401
#define FOLDEF_LEU_SolEne_CG    -0.295
#define FOLDEF_LEU_SolEne_CD1   -0.507
#define FOLDEF_LEU_SolEne_CD2   -0.507
#define FOLDEF_LYS_SolEne_CB    -0.401
#define FOLDEF_LYS_SolEne_CG    -0.401
#define FOLDEF_LYS_SolEne_CD    -0.401
#define FOLDEF_LYS_SolEne_CE    -0.401
#define FOLDEF_LYS_SolEne_NZ    3.6000
#define FOLDEF_MET_SolEne_CB    -0.401
#define FOLDEF_MET_SolEne_CG    -0.401
#define FOLDEF_MET_SolEne_SD    -0.250
#define FOLDEF_MET_SolEne_CE    -0.401
#define FOLDEF_TRP_SolEne_CB    -0.401
#define FOLDEF_TRP_SolEne_CG    -0.228
#define FOLDEF_TRP_SolEne_CD1   -0.339
#define FOLDEF_TRP_SolEne_CD2   -0.213
#define FOLDEF_TRP_SolEne_NE1   0.3200
#define FOLDEF_TRP_SolEne_CE2   -0.213
#define FOLDEF_TRP_SolEne_CE3   -0.339
#define FOLDEF_TRP_SolEne_CZ2   -0.339
#define FOLDEF_TRP_SolEne_CZ3   -0.339
#define FOLDEF_TRP_SolEne_CH2   -0.339
#define FOLDEF_SER_SolEne_CB    -0.401
#define FOLDEF_SER_SolEne_OG    0.9600
#define FOLDEF_THR_SolEne_CB    -0.295
#define FOLDEF_THR_SolEne_OG1   0.9600
#define FOLDEF_THR_SolEne_CG2   -0.507
#define FOLDEF_TYR_SolEne_CB    -0.401
#define FOLDEF_TYR_SolEne_CG    -0.228
#define FOLDEF_TYR_SolEne_CD1   -0.339
#define FOLDEF_TYR_SolEne_CD2   -0.339
#define FOLDEF_TYR_SolEne_CE1   -0.339
#define FOLDEF_TYR_SolEne_CE2   -0.339
#define FOLDEF_TYR_SolEne_CZ    -0.339
#define FOLDEF_TYR_SolEne_OH    0.8000
#define FOLDEF_VAL_SolEne_CB    -0.295
#define FOLDEF_VAL_SolEne_CG1   -0.507
#define FOLDEF_VAL_SolEne_CG2   -0.507
#define FOLDEF_HOH_SolEne_HOH   1.8000


#define FOLDEF_GEN_charge       0.0
#define FOLDEF_BKB_Charge_NTER  1.0
#define FOLDEF_BKB_Charge_CTER  -0.5
#define FOLDEF_ARG_Charge_NE    0.333
#define FOLDEF_ARG_Charge_NH1   0.333
#define FOLDEF_ARG_Charge_NH2   0.333
#define FOLDEF_ASP_Charge_OD1   -0.5
#define FOLDEF_ASP_Charge_OD2   -0.5
#define FOLDEF_GLU_Charge_OE1   -0.5
#define FOLDEF_GLU_Charge_OE2   -0.5
#define FOLDEF_LYS_Charge_NZ    1.0

int ALA_SetFOLDEFParameter(Atom *pAtomArray, int atomCount);
int GLY_SetFOLDEFParameter(Atom *pAtomArray, int atomCount);
int ARG_SetFOLDEFParameter(Atom *pAtomArray, int atomCount);
int ASN_SetFOLDEFParameter(Atom *pAtomArray, int atomCount);
int ASP_SetFOLDEFParameter(Atom *pAtomArray, int atomCount);
int CYS_SetFOLDEFParameter(Atom *pAtomArray, int atomCount);
int GLN_SetFOLDEFParameter(Atom *pAtomArray, int atomCount);
int GLU_SetFOLDEFParameter(Atom *pAtomArray, int atomCount);
int HIS_SetFOLDEFParameter(Atom *pAtomArray, int atomCount);
int ILE_SetFOLDEFParameter(Atom *pAtomArray, int atomCount);
int LEU_SetFOLDEFParameter(Atom *pAtomArray, int atomCount);
int LYS_SetFOLDEFParameter(Atom *pAtomArray, int atomCount);
int MET_SetFOLDEFParameter(Atom *pAtomArray, int atomCount);
int PHE_SetFOLDEFParameter(Atom *pAtomArray, int atomCount);
int PRO_SetFOLDEFParameter(Atom *pAtomArray, int atomCount);
int SER_SetFOLDEFParameter(Atom *pAtomArray, int atomCount);
int THR_SetFOLDEFParameter(Atom *pAtomArray, int atomCount);
int TRP_SetFOLDEFParameter(Atom *pAtomArray, int atomCount);
int TYR_SetFOLDEFParameter(Atom *pAtomArray, int atomCount);
int VAL_SetFOLDEFParameter(Atom *pAtomArray, int atomCount);
int NTER_SetFOLDEFParameter(Atom *pAtomArray, int atomCount);
int GLYP_SetFOLDEFParameter(Atom *pAtomArray, int atomCount);
int PROP_SetFOLDEFParameter(Atom *pAtomArray, int atomCount);
int CTER_SetFOLDEFParameter(Atom *pAtomArray, int atomCount);


#endif // FOLDED_H